"""commodity table

Revision ID: 1f0a11a360c7
Revises: d1d44b7fadeb
Create Date: 2022-12-24 13:25:41.722102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0a11a360c7'
down_revision = 'd1d44b7fadeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('interest_yield', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_cycle'), ['cycle'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_interest_yield'), ['interest_yield'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_name'))
        batch_op.drop_index(batch_op.f('ix_commodity_interest_yield'))
        batch_op.drop_index(batch_op.f('ix_commodity_cycle'))
        batch_op.drop_index(batch_op.f('ix_commodity_created_at'))

    op.drop_table('commodity')
    # ### end Alembic commands ###
