"""added amount_raised, funded to commodity table

Revision ID: e2e95a01e536
Revises: de11d162494e
Create Date: 2022-12-28 15:00:03.208782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e95a01e536'
down_revision = 'de11d162494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_raised', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funded', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_commodity_amount_raised'), ['amount_raised'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_funded'), ['funded'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_funded'))
        batch_op.drop_index(batch_op.f('ix_commodity_amount_raised'))
        batch_op.drop_column('funded')
        batch_op.drop_column('amount_raised')

    # ### end Alembic commands ###
