"""added location, duration, amount to commodity table

Revision ID: 4e968467a715
Revises: d9afde1c920c
Create Date: 2022-12-27 23:34:55.319468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e968467a715'
down_revision = 'd9afde1c920c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_commodity_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_location'), ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_location'))
        batch_op.drop_index(batch_op.f('ix_commodity_duration'))
        batch_op.drop_index(batch_op.f('ix_commodity_amount'))
        batch_op.drop_column('duration')
        batch_op.drop_column('location')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
