"""changed maturity to maturity_date on investment table

Revision ID: 5fed209a6fcb
Revises: 85b0eac7f6f8
Create Date: 2022-12-30 20:16:23.134899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fed209a6fcb'
down_revision = '85b0eac7f6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maturity_date', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_investment_maturity')
        batch_op.create_index(batch_op.f('ix_investment_maturity_date'), ['maturity_date'], unique=False)
        batch_op.drop_column('maturity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maturity', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_investment_maturity_date'))
        batch_op.create_index('ix_investment_maturity', ['maturity'], unique=False)
        batch_op.drop_column('maturity_date')

    # ### end Alembic commands ###
