"""added commodity thumbnail to commodity table

Revision ID: bdd6b8c11223
Revises: e2e95a01e536
Create Date: 2022-12-28 15:02:39.319417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd6b8c11223'
down_revision = 'e2e95a01e536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_thumbnail', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_column('location_thumbnail')

    # ### end Alembic commands ###
