"""added category to commodity table

Revision ID: de11d162494e
Revises: 4e968467a715
Create Date: 2022-12-27 23:49:44.619779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de11d162494e'
down_revision = '4e968467a715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_commodity_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_location'), ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_location'))
        batch_op.drop_index(batch_op.f('ix_commodity_duration'))
        batch_op.drop_index(batch_op.f('ix_commodity_category'))
        batch_op.drop_index(batch_op.f('ix_commodity_amount'))
        batch_op.drop_column('category')
        batch_op.drop_column('duration')
        batch_op.drop_column('location')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
