"""removed funded field from commodity table

Revision ID: 6e29ba864b99
Revises: 94da65eb541c
Create Date: 2023-01-08 12:22:30.763697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e29ba864b99'
down_revision = '94da65eb541c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_index('ix_commodity_funded')
        batch_op.drop_column('funded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funded', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_commodity_funded', ['funded'], unique=False)

    # ### end Alembic commands ###
