"""investment table

Revision ID: aac7f7bc05d4
Revises: 1f0a11a360c7
Create Date: 2022-12-24 13:27:02.086586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac7f7bc05d4'
down_revision = '1f0a11a360c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_', sa.String(length=255), nullable=True),
    sa.Column('investment_yield', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('maturity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_investment_yield'), ['investment_yield'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_maturity'), ['maturity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_maturity'))
        batch_op.drop_index(batch_op.f('ix_investment_investment_yield'))
        batch_op.drop_index(batch_op.f('ix_investment_amount'))

    op.drop_table('investment')
    # ### end Alembic commands ###
