DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS investment;
DROP TABLE IF EXISTS commodity;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  id_ TEXT UNIQUE NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  date_of_birth DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE commodity (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  id_ TEXT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  cycle INTEGER NOT NULL,
  interest_yield FLOAT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE investment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  id_ TEXT UNIQUE NOT NULL,
  investor_id INTEGER NOT NULL,
  commodity_id INTEGER NOT NULL,
  investment_yield FLOAT NOT NULL,
  amount FLOAT NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE,
  maturity_date TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (investor_id) REFERENCES user (id)
  FOREIGN KEY (commodity_id) REFERENCES commodity (id)
);